data:
  root_dir: 'data'
  batch_size: 32
  num_workers: 6

model:
  name: 'simple_cnn'
  num_classes: 9
  dropout_rate: 0.3

training:
  num_epochs: 15
  learning_rate: 0.001
  optimizer: 'adam'
  evaluate_every: 5
  weight_decay: 0.0001
  scheduler:
    name: 'cosine_annealing_warm_restarts'
    T_0: 20
    T_mult: 5
  early_stopping:
    patience: 15
    min_delta: 0.001

data_augmentation:
  random_rotation: 0
  random_horizontal_flip: true
  random_vertical_flip: false
  color_jitter:
    brightness: 0.0
    contrast: 0.0
    saturation: 0.0
    hue: 0.0

seed: 42

paths:
  best_model: 'results/simple_cnn_best_model.pth'
  confusion_matrix: 'results/simple_cnn_confusion_matrix.png'
  learning_curves: 'results/simple_cnn_learning_curves.png'
  log_dir: 'logs/simple_cnn'
  metrics: 'results/simple_cnn_metrics.json'