data:
  root_dir: 'data'
  batch_size: 32
  num_workers: 6

model:
  name: 'neural_net'
  num_classes: 9

training:
  num_epochs: 5
  learning_rate: 0.001
  optimizer: 'adam'
  evaluate_every: 5

seed: 42

paths:
  best_model: 'results/neural_net_best_model.pth'
  confusion_matrix: 'results/neural_net_confusion_matrix.png'
  learning_curves: 'results/neural_net_learning_curves.png'
  log_dir: 'logs/neural_net'
  metrics: 'results/neural_net_metrics.json'