data:
  root_dir: 'data'
  batch_size: 32
  num_workers: 8

model:
  name: 'advanced_cnn'
  num_classes: 10
  dropout_rate: 0.5

training:
  num_epochs: 100
  learning_rate: 0.001
  optimizer: 'adam'
  evaluate_every: 20
  weight_decay: 0.0001
  scheduler:
    name: 'cosine_annealing_warm_restarts'
    T_0: 10
    T_mult: 2
  early_stopping:
    patience: 15
    min_delta: 0.001

data_augmentation:
  random_rotation: 15
  random_horizontal_flip: true
  random_vertical_flip: false
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

seed: 42

paths:
  best_model: 'results/advanced_cnn_best_model.pth'
  confusion_matrix: 'results/advanced_cnn_confusion_matrix.png'
  learning_curves: 'results/advanced_cnn_learning_curves.png'
  log_dir: 'logs/advanced_cnn'
  metrics: 'results/advanced_cnn_metrics.json'