# config.yaml

data:
  root_dir: 'C:\Users\joewh\OneDrive\Desktop\Mulit-class-Classification-Network\data\'
  batch_size: 32
  num_workers: 4

model:
  name: 'simple_cnn'  # Options: 'logistic', 'simple_cnn', 'resnet50'
  num_classes: 10

training:
  num_epochs: 50
  learning_rate: 0.001
  optimizer: 'adam'  # Options: 'adam', 'sgd'
  evaluate_every: 10
  scheduler:
    name: 'reduce_lr_on_plateau'
    patience: 5
    factor: 0.1

seed: 42

paths:
  best_model: 'results/best_model.pth'
  confusion_matrix: 'results/confusion_matrix.png'
  learning_curves: 'results/learning_curves.png'